language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'FakeCompany' ]; then cd .. && eval "mv $currentfolder FakeCompany" && cd FakeCompany; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
